# Generated by Django 5.2.5 on 2025-08-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='item_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
