# Generated by Django 5.2.5 on 2025-09-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_access_token_customuser_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='item_id',
        ),
    ]
